server:
    port: 9191 

spring:
    application:
        name: API-GATEWAY

cloud:
    gateway:
        routes:
            - id: USER_SERVICE
              uri: 'lb://USER-SERVICE'
              predicates: 
                  - path=/users/**
            - id: DEPARTMENT_SERVICE
              uri: 'http://localhost:8001'
              #uri: 'http://DEPARTMENT-SERVICE/'
              predicates:
                  -Path=/departments/**
