server:
    port: 9296 

spring:
    application:
        name: cloud-config
cloud:
    config:
        server:
            git:
                uri: 'https://github.com/maddscorpian/springexample/tree/main/could-config'
                clone-on-start: true
                skipSslValidation: true
